### PR TITLE
Mark EventStore based I/O as deprecated

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Introduce deprecation warnings for the **EventStore based I/O model** as it **will be removed in favor of the `Frame` based one**

ENDRELEASENOTES

In order to pass CI deprecation warnings are temporarily accepted and this exception has to be taken back again when the EventStore code is removed.

### CODE REVIEW

**Comment by tmadlener** [comment]
The edm4hep workflow currently fails because it still uses the `EventStore` until key4hep/EDM4hep#184 is merged. I suggest we wait for that to go in first, and the merge this.

**Comment by hegner** [comment]
@tmadlener - before merging we have to get the Gaudi part fixed as well.

**Comment by tmadlener** [comment]
In principle this can be merged even without those fixes since we are only introducing a few deprecation warnings and not yet removing anything. But since this is not extremely urgent we can also wait.

**Comment by hegner** [comment]
@tmadlener - actually it is errors in the current setup. Otherwise the PR checks would succeed ;-)

**Comment by tmadlener** [comment]
The errors are deprecation warnings that are triggered in the EDM4hep build. They should be fixed by key4hep/EDM4hep#194 and key4hep/EDM4hep#182

**Comment by tmadlener** [comment]
All downstream (EDM4hep) fixes have been merged, so I think this could be merged.

**Review by hegner — APPROVED** [review]

**Pull request merged**
