### PR TITLE
FCC downstream changes

### PR DESCRIPTION
**Pull request by vvolkl**
BEGINRELEASENOTES

- ROOTReader now supports multiple inputs thanks to new implementation based on TChain 
- ROOTReader now supports opening files via xrootd (`root:///eospublic.cern.ch//eos...` for example)
- Improved CMake and CPack configuration, sticking more closely to HSF template

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
@vvolkl could you please resolve the conflicts of this PR, before we can merge it.

**Comment by vvolkl** [comment]
Hi Frank @gaede,

I checked, and while it's not possible to rebase the PR, you should be able to merge it creating a merge request (just select that option from the dropdown menu on the rebase button). Since we already pushed those commits to the master in the FCC fork, it would be highly appreciated if I didn't have to rewrite them.
Cheers,
Valentin

**Comment by gaede** [comment]
Hi Valentin,
ok fine with me, just let me know when you're done.
Cheers, Frank.

**Comment by vvolkl** [comment]
Right! Yes, no other developments currently, so it's fine to merge. We already did a 0.9.1 release as these  changes are needed in production. Thanks

**Pull request merged**
