### PR TITLE
[WIP] Schema evolution code generation

### PR DESCRIPTION
**Pull request by hegner**
BEGINRELEASENOTES
- Thank you for writing the text to appear in the release notes. It will show up
  exactly as it appears between the two bold lines
- ...

ENDRELEASENOTES

Based on #430 
- [ ] Needs #460

### CODE REVIEW

**Comment by tmadlener** [comment]
> Based on https://github.com/AIDASoft/podio/pull/430

Just for my clarification from my side: This means we still keep 430 as it is and merge it separately, or we close that and keep this one for the feature?

**Comment by hegner** [comment]
Since I am fixing bugs in #430, I think we better close it. I previously thought functionality in there was stable.

**Comment by tmadlener** [comment]
Rebased this onto #460. For me locally there are a few test issues with the datamodel storage roundtrip tests, because they now trip over the fact that for the schema evolution tests we generate "old" `Data.h` headers into the same directory. This makes the final `diff` step in those tests fail.

I don't have a real fix for that yet, but I would simply wait for now to see how the final solution to schema evolution looks like and then fix those tests afterwards.

**Comment by hegner** [comment]
Since based on #430 , this development will not be integrated.

**Pull request closed without merging**
