### PR TITLE
update CI to use use newer LCG views

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- Update CI actions to use LCG 96, 97, 98 for mac, centos7 and ubuntu1804

ENDRELEASENOTES
Should resolve the issue caused by the update of the virtual enviroment #137

### CODE REVIEW

**Comment by petricm** [comment]
Why the `pyunittest` fails for ROOT 6.22 and not for 6.20 I don't know.

**Comment by petricm** [comment]
Seems that `pyunittest` does also not work on linux with ROOT 6.22, just wait that the PR CI finishes.

**Comment by tmadlener** [comment]
Hi @petricm,
The failure of the `pyunittest` is looking like an "actual" failure this time and not the one described in #137. I am not entirely sure why this seems to fail just now, because the tests ran succesfully under python3 before, but the failure is consistent for `linux` and `mac` and the original issue seems to be resolved.

**Comment by petricm** [comment]
@tmadlener this is not a issue of python versions but of ROOT versions. LCG_98=ROOT 6.22 and LCG_97=ROOT 6.20. You did no test 6.22 before.

**Comment by tmadlener** [comment]
Ah, I see. Thanks for clarifying.

**Comment by tmadlener** [comment]
I am not entirely sure why this breaks with root 6.22.00, but didn't with 6.20.04. The problem is that when we try to loop over a collection in python, the `__getitem__` method gets called and that usually expects two arguments: `self` and an index. It seems that in our case the `__getitem__` method gets called with only one argument and, hence, complains about a missing positional argument.

In any case, not overriding the `__getitem__` method as we currently do, but letting `cppyy` seems to get rid of the problem. I have opened #141 with the necessary changes.

**Comment by tmadlener** [comment]
The ubuntu build seems to be failing because ROOT defines it's own `string_view`, resp. aliases the one from `experimental/string_view`. Could it be that the dictionary generation picks up the wrong c++ standard? I couldn't find the c++ standard with which the root release used in the docker image is built, but is it possible that it is not c++17? At least locally on Ubuntu 20.04 I can build podio against root 6.22, when I also use c++17 for building root.

**Comment by tmadlener** [comment]
With the changes from #141 applied on top of this one all workflows look good, apart from the ubuntu one, which still fails during the build:
[mac](https://github.com/tmadlener/podio/actions/runs/259629585)
[linux](https://github.com/tmadlener/podio/actions/runs/259629587)
[python](https://github.com/tmadlener/podio/actions/runs/259629576)
[ubuntu](https://github.com/tmadlener/podio/actions/runs/259629577)

**Comment by petricm** [comment]
@tmadlener you are right, the ubuntu root has the flags `-pthread -std=c++11 -m64 -I/opt/root/include`, but I would advice that you inherit the CXX standard from ROOT and not set it explicitly like here 

https://github.com/AIDASoft/podio/blob/d4a02651332e2fe3ffbac4e99fa61b34600a16fa/CMakeLists.txt#L37

**Comment by petricm** [comment]
I have removed the ubuntu image update

**Comment by tmadlener** [comment]
> @tmadlener you are right, the ubuntu root has the flags `-pthread -std=c++11 -m64 -I/opt/root/include`, but I would advice that you inherit the CXX standard from ROOT and not set it explicitly like here


The problem is that podio is using some features that are only available in c++17. The switch to c++14 was done 4 years ago. However, it is possible that compiling it with a lower standard was still possible for some time. The decision to switch to c++17 for podio (and edm4hep) was made a few months back. so in that regard, switching back to c++14 would probably be possible, but I would really not like to do so, because c++17 has some really nice features, and it is 2020 after all ;)

**Comment by petricm** [comment]
I completely agree. It would be however still good for the user that you check the ROOT libs for their `target_compile_features` and check if they have the same standard as you are building podio and if not break at the cmake step.

**Comment by vvolkl** [comment]
@petricm agreed - I usually build podio with spack, where the recipe already is updated with the correct root dependency, but it's a good idea nonetheless.

**Comment by tmadlener** [comment]
That is a very good idea indeed. I have added it to #141 

CI runs with the changes of this PR and #141 can be found here:
- [ubuntu](https://github.com/tmadlener/podio/actions/runs/260861294)
- [python](https://github.com/tmadlener/podio/actions/runs/260861293)
- [linux](https://github.com/tmadlener/podio/actions/runs/260861292)
- [mac](https://github.com/tmadlener/podio/actions/runs/260861291)

**Comment by tmadlener** [comment]
Should we merge this PR with #141, so that it is easier to see that the combination of the two fixes the current issues with the CI?

**Comment by petricm** [comment]
Replace the ubuntu root image with the ubutu LCG view

**Comment by petricm** [comment]
@tmadlener cherry-pick my PR into yours and copy the release notes.

**Comment by tmadlener** [comment]
> @tmadlener cherry-pick my PR into yours and copy the release notes.

Done

**Pull request closed without merging**
