### PR TITLE
add documentation

### PR DESCRIPTION
**Pull request by soumilbaldota**
Add Julia documentation

### CODE REVIEW

**Comment by soumilbaldota** [comment]
The blog post and the docstrings cover the functions documentation pretty well so I think this is complete.  @tmadlener If you have any suggestions please let me know.

**Comment by tmadlener** [comment]
@soumilbaldota Looks good to me. Just leaving this open, until the GSoC blog post is merged and published, so that we can add a link to that also here.

**Comment by soumilbaldota** [comment]
@tmadlener which file should I add the link to the blog post or should a comment here suffice.

**Comment by tmadlener** [comment]
I would put it into `.md` file. Maybe add a brief paragraph to the `template.md` stating that the Julia code generation was done as part of GSoC and link to the blog there.

**Pull request merged**
